### ISSUE TITLE
"My Matches" filter still shows all matches

### ISSUE THREAD

**Issue by melsonius** [riddlesio/issues#1]
As you can see in the attached screenshot, selecting "My Matches" in the match log doesn't show only my matches.  

![2017-05-10](https://cloud.githubusercontent.com/assets/2984769/25899431/d3abfb0e-355d-11e7-888a-8f86046c779c.png)

**Comment by nikovanmeurs** [comment]
Thanks for the heads up!

We deployed a fix about an hour ago. Please let us know if it works for you.

**Comment by melsonius** [comment]
Looks like it's working, thanks for the quick response!
