### ISSUE TITLE
C# starter bot to MsHackman

### ISSUE THREAD

**Issue by will-lucena** [riddlesio/issues#101]
We using MsHackman to learn AI at a discipline from IT course on UFRN (Federal University of Rio Grande do Norte, Brazil) and I decide to make a c# bot based on Java starter bot code on the site.
That is the link to my git repository for this project, it isn't documented yet but it's funcional: https://github.com/will-lucena/MsHackManBot.git

**Comment by JimVanEeden** [comment]
Thank you so much for your efforts! Unfortunately I could not get the bot to work, it doesn't return any output. If you can fix this, I can make it publicly available for everyone.

**Comment by will-lucena** [comment]
Sorry, I forgot to commit my last changes when I fixed it. Now is right and with a readme. Thanks for the feedback

**Comment by JimVanEeden** [comment]
Thank you, it's available now :)
