### ISSUE TITLE
Docker images missing?

### ISSUE THREAD

**Issue by wild8oar** [riddlesio/issues#106]
When compiling/testing my four-in-a-row bot, I receive error messages like these:

`Unable to find image 'gcr.io/riddles-microservices/sandbox-compiler-java:e3b4f56-be276daa6de9' locally
Pulling repository gcr.io/riddles-microservices/sandbox-compiler-java
docker: unauthorized: authentication required.
See 'docker run --help'.`

or

`Unable to find image 'gcr.io/riddles-microservices/sandbox-compiler-java:e3b4f56-be276daa6de9' locally
Pulling repository gcr.io/riddles-microservices/sandbox-compiler-java
docker: Error: Status 405 trying to pull repository riddles-microservices/sandbox-compiler-java: "v1 Registry API is disabled. If you are not explicitly using the v1 Registry API, it is possible your v2 image could not be found. Verify that your image is available, or retry with `dockerd --disable-legacy-registry`. See https://cloud.google.com/container-registry/docs/support/deprecation-notices".
See 'docker run --help'.`

**Comment by surajsonawane111** [comment]
i am facing the exact same issue, while uploading a zip file for light rider since last 24 hrs.

**Comment by JimVanEeden** [comment]
Sorry guys we suffered some issues in our backend over the weekend, but that's been fixed now. You can upload your bots again.
