### ISSUE TITLE
"Upload bot" in green bar not working 

### ISSUE THREAD

**Issue by WardBeullens** [riddlesio/issues#11]
If I upload a bot via the green bar my bot is wrongly classified as a C bot. If I submit the same zip file via the 'upload new revision' button on the overview page it is correctly recognized as a Python 3 bot. 

EDIT: Now I got a bot that was classified as  a C bot, even though I uploaded it via the overview page. After uploading the same files a second time it did work. So there is some kind of problem, but it is probably not related to which button is used.

**Comment by nikovanmeurs** [comment]
We've seen this issue before with some bots that were built using Visual Studio. We detect the language based on the file extension and visual studio adds a project meta folder containing one or more files with a .c extension. Could you check and let us know if this happens in your case?

**Comment by WardBeullens** [comment]
I made the solution in the PyCharm IDE, there are no .c files, but there are a number of extra files with .pyc , .name , .iml and .xml extensions.

**Comment by JimVanEeden** [comment]
What happens if you actually only compress/upload the source files?

**Comment by WardBeullens** [comment]
It works fine if I do so
