### ISSUE TITLE
Moves take far longer to run on site than locally

### ISSUE THREAD

**Issue by RenegadeLucien** [riddlesio/issues#12]
When I test my bot locally, it takes 30-50ms to make a move, depending on the input state. But in games on the site, most notably my challenge against "Dalek", many moves, particularly the opening moves, exhausted the entire 500ms allocated per move and started dipping into the time bank. What could exist on the server that could explain this discrepancy? Or is the time it takes for the site to give us the next state counted against us?

**Comment by nikovanmeurs** [comment]
We're aware of the issue, unfortunately we cannot offer a quick solution at this point in time. If other bots are pondering, they're using resources during your move. These resources are currently shared and we currently don't have the means in place to detect and disqualify bots that continue their calculations during the opponents' time.

We have plans to rework the way we currently run matches and at least split up the resource allocation, but we're not exactly sure yet when we're able to start working on this.

I'll leave this issue open and reply here when we start working on this.

**Comment by RenegadeLucien** [comment]
To add onto this, I recently added iterative deepening to Renegade and set it to not go any deeper if the bot had spent over 200ms on the  move. I tried many sample positions locally and it never resulted in a move taking longer than 400ms. On the server, I timed out in seven rounds with some moves taking upwards of three seconds, a move length that shouldn't even be possible for my bot given the low branching factor of the game tree.

**Comment by jabbink** [comment]
Computers use different CPU's and your home computer is probably a lot faster than the server this is run on.

As comparison, on my a-few-years-old laptop with an old i7 in powersave mode I get ~100k full board evaluations (minmax) per second. On the server 10k-30k/s.

**Comment by jmcarthur** [comment]
I do think something seems really weird, though. The current version of my bot literally just walks one path a few levels into the game tree, samples the time, and repeats, until it has exhausted only 1/3 of its time bank. I had to turn it down from 1/2 just to get past the input test.

**Comment by JimVanEeden** [comment]
We're working on an overhaul of the match environment at the moment. That should solve a lot of the problems. If not, we'll dive deeper into what is causing these issues.
