### ISSUE TITLE
Documentation says 500 ms/move, game actually gives only 100 ms/move

### ISSUE THREAD

**Issue by melsonius** [riddlesio/issues#13]
Under Rules > Technical details, it says "You get an initial maximally filled timebank of 10 seconds and each time a move is requested 500ms will be added to your timebank."  However, the game is actually configured to give only 100 ms per move ("settings time_per_move 100" in the IO logs).

Personally I think 100 ms is a criminally short amount of time per turn, but I think that discussion has already been had to death over at theaigames.com.

**Comment by nikovanmeurs** [comment]
@JimVanEeden can you look into this?

**Comment by JimVanEeden** [comment]
Will be fixed somewhere this week.

**Comment by JimVanEeden** [comment]
We're working on making the game settings easily configurable per competition. In the mean time I've updated the rules and getting started pages so they reflect what the engine actually gives at the moment, which is 100ms

**Comment by JimVanEeden** [comment]
Alright the settings have been changed to 200 ms as we intended from the start, documentation has been updated accordingly.
