### ISSUE TITLE
Java starter bot has method for maximum rounds but the game never sends the setting

### ISSUE THREAD

**Issue by melsonius** [riddlesio/issues#14]
In this case, it seems it's the Java starter bot that's in error, as the game engine sends exactly the settings listed in the documentation.  

However, the starter bot has a BotState.MAX_ROUNDS (and associated getter and setter) that is never initialized (unlike all of the other values in the state object).  Nothing major, just something that might confuse people.

**Comment by nikovanmeurs** [comment]
Thanks for letting us know. @JimVanEeden can you fix this?

**Comment by JimVanEeden** [comment]
You're right, fixed now. Thanks :)
