### ISSUE TITLE
No matches in 13+ hrs

### ISSUE THREAD

**Issue by melsonius** [riddlesio/issues#15]
As of 2pm EST, my bot hasn't had any matches, including a couple of manually initiated challenges (see most recently https://starapple.riddles.io/competitions/light-riders/matches/95c3a96d-d52c-4ff9-80cd-9c5a0bb21dbe).

My test match went off without a hitch and there seem to be plenty of other matches going on, so I'm not sure what's happening.

**Comment by melsonius** [comment]
I've uploaded a few new versions since then, and I'm still not getting any automatic matches.  However, I am able to successfully challenge a few other bots, but most of the time challenges just end up result in an infinite spinning "Waiting for match to be played....".  It looks like it's consistent between bots.  For example, I can challenge Rhea with no problems, but [INSAT]Elirso results in the nothing at all.

**Comment by JimVanEeden** [comment]
We think we know what the problem is. The matches are not stored correctly when one of the two bots crashes. Will be fixed today, thank you for your report :)

**Comment by JimVanEeden** [comment]
Correction, will be fixed tomorrow.

**Comment by nikovanmeurs** [comment]
This should be fixed now.

**Comment by melsonius** [comment]
Yup, looks like it's working now, thanks!
