### ISSUE TITLE
Compile is failing without output

### ISSUE THREAD

**Issue by SimonPrins** [riddlesio/issues#16]
My bot is failing the compilation step, however no output is shown in the submission details.
In the Submission logs, the Compile step is stuck displaying a loading icon.
My bot does compile locally (At least the last version I uploaded does).

**Comment by SimonPrins** [comment]
I at least found out what seemed to be the problem.
There was a .metadata folder added by Eclipse, which seems to have caused the compilation to fail on the server.

**Comment by trogatog** [comment]
I'm still having this issue with my C# bot. Output would definitely be handy

**Comment by nikovanmeurs** [comment]
@trogatog could you send your bot to niko [at] riddles [dot] io? I'd like to take a look at it to see if I can figure out why you're not getting any feedback from the compiler.

**Comment by nikovanmeurs** [comment]
@SimonPrins thanks for letting us know. I'll be adding some functionality to filter out IDE metadata folders when doing the programming language detection in the near future as I'm working on several compiler and input test related issues at the moment.

**Comment by nikovanmeurs** [comment]
We just deployed an update which fixes several bugs, any of which could cause a log to not be shown. Please let us know if you are still experiencing issues.
