### ISSUE TITLE
Kotlin starter bot

### ISSUE THREAD

**Issue by jabbink** [riddlesio/issues#17]
https://github.com/jabbink/light-riders-starter-bot

Can be compiled with `kotlinc`

Kotlin runtime should be on the classpath while executing.

**Comment by JimVanEeden** [comment]
Thanks a lot :)

I'll probably have a look at implementing Kotlin next week.

**Comment by nikovanmeurs** [comment]
We have tentative support for Kotlin in our test environment. We'll deploy the update tomorrow if everything works as expected.

**Comment by nikovanmeurs** [comment]
The sandbox has been updated, we now have support for Kotlin.

Have fun coding!
