### ISSUE TITLE
Unable to download Java starterbot

### ISSUE THREAD

**Issue by jmerle** [riddlesio/issues#18]
The Java starterbot on the [Getting Started page of the Light Riders](https://starapple.riddles.io/competitions/light-riders/getting-started) contest links to a page which just shows the following error:

https://storage.googleapis.com/riddles-production/lightriders-starterbot-java.zip
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access denied.</Message>
    <Details>Anonymous users does not have storage.objects.get access to object riddles-production/lightriders-starterbot-java.zip.</Details>
</Error>
```

I can download the C and C# starterbots just fine, though.

**Comment by JimVanEeden** [comment]
Wups, I forgot to make the file publicly accessible when I updated the bot. Thanks for your report. Fixed now.
