### ISSUE TITLE
Compiling no longer works

### ISSUE THREAD

**Issue by jmerle** [riddlesio/issues#19]
Hi,

It seems like compiling Javascript bots is no longer possible at all. Both my newer bot aswell as my first bot (which did compile succesfully before and is my currently running bot) show the same two errors:

```
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
: /compiler_dir/compile.sh: No such file or directory
```

The first one doesn't bother me since I know you guys are aware of it, but the second one is kinda unusual, and judging by the message it is the reason why compiling isn't working.

**Comment by nikovanmeurs** [comment]
We had a misconfigured version of the match-runner/compiler running for about 20 minutes. The problem should be fixed now.

**Comment by jmerle** [comment]
I am still seeing the same two messages on re-upload.

**Comment by nikovanmeurs** [comment]
I'm looking into it right now. By the way, the warning about swap limit capabilities is shown on all compiles and has been there since the start.

**Comment by nikovanmeurs** [comment]
The problem should be solved now. Please let us know if you're still experiencing problems.

**Comment by jmerle** [comment]
Yep, it works! Thanks!
