### ISSUE TITLE
Website not compiling new bots / Running any games right now, for 6+ hours

### ISSUE THREAD

**Issue by Elirso** [riddlesio/issues#2]
Right now all my updates are stuck on input test. Also seems like no additional matches are being played

**Comment by JimVanEeden** [comment]
Thank you, there seems to be some problem indeed. We will fix this asap.

**Comment by melsonius** [comment]
Probably related, but the Match Log won't load at all right now (tried on both phone and Mac laptop including a forced refresh).

**Comment by JimVanEeden** [comment]
Yes this is related, there is some data issue going on with the matchrunner. Should hopefully be fixed today.

**Comment by nikovanmeurs** [comment]
The backend services have been patched, both issues should be resolved now. Please let us know if you're still experiencing issues while uploading bots.

**Comment by Elirso** [comment]
Okay, this seems to be fixed. Thank you ! 
Just, one last issue, I have the revisions of my bot # 4 to 8 that are still waiting to have their input test done; Is it possible to delete them or make the test go through ? Just disturbing.
