### ISSUE TITLE
Lost rating for a win

### ISSUE THREAD

**Issue by RenegadeLucien** [riddlesio/issues#20]
My bot, Renegade, won [this game](https://starapple.riddles.io/competitions/light-riders/matches/e8cf7b01-911a-4399-a1cc-3186298b30c0) but still lost 1 rating point.

**Comment by nikovanmeurs** [comment]
This is actually not a bug. To shamelessly quote the [TrueSkill FAQ](https://www.microsoft.com/en-us/research/project/trueskill-ranking-system/) here:

> Surprisingly, this is not a bug and it happens when players with very small σ but widely varying μ get matched together (thanks to rugdivot for figuring this out).
> 
> So, what is going on here? Between any two games of a gamer, the TrueSkill ranking system assumes that the true skill of a gamer, that is, μ, can have changed slightly either up or down; this property is what allows the ranking system to adapt to a change in the skill of a gamer. Technically, this is achieved by a small increase in the σ of each participating gamer before the game outcome is incorporated. Usually, a game outcome provides enough pieces of information to reduce this increased uncertainty. But, in a badly matched game (as the one described above) this is not the case; in this case, nothing can be learned about the winner from the game outcome (because it was already known before the game that the winner was significantly higher ranked than the other gamers he has beaten). So, conservatively speaking, the winner’s skill might have slightly decreased! Note that this can only happen if the gamer is not matched correctly so that he can “prove” to the TrueSkill ranking system that his skill has not changed.
