### ISSUE TITLE
golang starter bot

### ISSUE THREAD

**Issue by vendelin8** [riddlesio/issues#21]
Hi,

I created a starter bot in golang referring to this thread:
https://starapple.riddles.io/competitions/light-riders/discussions/discussion/c507fefe-fd85-4061-833c-6faa0b1dc6f9/1
Please check it out here:
https://github.com/vendelin8/lightriders-starterbot-golang

Cheers

**Comment by JimVanEeden** [comment]
Thanks! I'm going to work on it this week, together with OCaml and Kotlin. Can't give any promises yet that it's going to work though, but I'll keep you updated.

**Comment by vendelin8** [comment]
Okay, thank you!

**Comment by royerk** [comment]
Cool ! Thanks :+1:

**Comment by nikovanmeurs** [comment]
We have tentative support for OCaml, Kotlin and Go in our test environment. We'll deploy the update tomorrow if everything works as expected.

**Comment by JimVanEeden** [comment]
@vendelin8 Your starterbot does not work on the Riddles environment. I believe it is because it pulls stuff from github? Don't know Go very well but it looks like it. Anyways, we don't allow internet connection for security reasons.

All languages work correctly and we're deploying to production in a couple of minutes

**Comment by nikovanmeurs** [comment]
The sandbox has been updated, we now have support for Go.

Have fun coding!

**Comment by vendelin8** [comment]
@JimVanEeden it doesn't use internet at runtime. I found out, that to be able to run, all dependencies must be downloaded. The full process (I just did it onmy linux machine, it worked):
1. set GOPATH environment variable
2. download the project itself
3. download dependencies, the ```...``` at the end is necessary
```
export GOPATH=<the path to install go environment to>
go get github.com/vendelin8/lightriders-starterbot-golang
go get github.com/vendelin8/lightriders-starterbot-golang/lightRiders-starterBot-go/...
```
Then to build the project, call
```
go install github.com/vendelin8/lightriders-starterbot-golang/lightRiders-starterBot-go
```
It generates a binary at ```$GOPATH/bin/lightRiders-starterBot-go```
For omitting saving replays, add a ```-R``` switch after the filename. Please try it one more time, to be sure. Thanks!

**Comment by JimVanEeden** [comment]
Yes I got it to work locally, except in our environment we need all the files present in the uploaded .zip, because we can't allow internet, even for compilation. So what we do is run the following to compile the bot:
````
find "$SOURCE_DIR" -name '*.go' -print0 | xargs -0 go build -o "$BIN_DIR/run_ai"
````
This compiles the bot to a file called run_ai, and we run that.

**Comment by vendelin8** [comment]
Thanks for the info and for making this possible. Please write this info to the getting started page if you can. The Go starterbot is now located to the php starterbot. There's another starter bot at https://github.com/royerk/GoLightRiders-StarterBot , it could be added to the description too, maybe someone likes it better.

Thanks again.

**Comment by JimVanEeden** [comment]
Yes that was a small bug from earlier, is fixed now.

We're going to create a languages page in a little while which will explain all this stuff a bit better, so that should help with this :)
