### ISSUE TITLE
Unable to upload files over 1 MB. 

### ISSUE THREAD

**Issue by eric-clinch** [riddlesio/issues#25]
My bot for the Light Riders competition relies on a relatively large file of pre-computed values (3.53 MB). After my bot folder is zipped, it's 2.02 MB, well below the 5 MB file size limit. However, whenever I try uploading my bot, it fails and I get a message saying "Your bot could not be uploaded". After some testing, I have found that any upload over 1 MB fails. Specifically, I was able to upload a .99 MB file, but unable to upload a 1.00 MB file. I have tried uploading from different browsers (Chrome, Firefox, and Edge), but it failed on all of them if the file was over 1 MB.

**Comment by nikovanmeurs** [comment]
Thanks for letting us know. We'll fix the problem before the weekend.

**Comment by nikovanmeurs** [comment]
The issue should be fixed. Please let us know if you're still experiencing problems.
