### ISSUE TITLE
No Activation email

### ISSUE THREAD

**Issue by BoltonBailey** [riddlesio/issues#26]
I signed up for the riddles.io website, and was told I would receive an account activation email, but I received no such email.

**Comment by nikovanmeurs** [comment]
Thanks for letting us know. The problem has been fixed, so you should shortly receive the activation mail.

**Comment by WETErokAI** [comment]
I have the same issue.

**Comment by JimVanEeden** [comment]
We had a problem with our mailer, which is fixed now. I've manually activated your account, you can log in now :) Sorry for the inconvenience.
