### ISSUE TITLE
[Light Riders] Upload failed for unknown reason

### ISSUE THREAD

**Issue by barisdemirdelen** [riddlesio/issues#27]
When I try to upload a new bot, it first gets to the compilation stage, but later fails at upload stage and just says Upload failed for unknown reason.

I can not upload even the currently active bot again.

**Comment by melsonius** [comment]
I'm also seeing this.  I was able to get this error trace out of the browser's dev console, though it doesn't look particularly helpful:

{,…}
code
:
500
message
:
"Traceback (most recent call last):↵  File "/riddles/app/api/dispatcher.py", line 62, in wrapper↵    response = dispatch(self, *args, **kwargs)↵  File "/riddles/app/api/handlers/upload_handler.py", line 41, in post↵    output = methods[request_type](current_user)↵  File "/riddles/app/api/handlers/upload_handler.py", line 63, in upload_bot↵    botfile_name = self._upload_bot(botfile, content_type, bot.key.value, new_revision_nr)↵  File "/riddles/app/api/handlers/upload_handler.py", line 240, in _upload_bot↵    cloud_storage.upload_file(botfile_name, botfile, CODE_BUCKET, content_type)↵  File "/riddles/app/cloud_storage/cloud_storage.py", line 10, in upload_file↵    return google_upload(bucket, filename, filecontent, mimetype)↵  File "/riddles/app/cloud_storage/google.py", line 47, in object_insert↵    response = request.execute()↵  File "/usr/local/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper↵    return wrapped(*args, **kwargs)↵  File "/usr/local/lib/python3.6/site-packages/googleapiclient/http.py", line 833, in execute↵    method=str(self.method), body=self.body, headers=self.headers)↵  File "/usr/local/lib/python3.6/site-packages/googleapiclient/http.py", line 173, in _retry_request↵    raise exception↵  File "/usr/local/lib/python3.6/site-packages/googleapiclient/http.py", line 160, in _retry_request↵    resp, content = http.request(uri, method, *args, **kwargs)↵  File "/usr/local/lib/python3.6/site-packages/oauth2client/transport.py", line 175, in new_request↵    redirections, connection_type)↵  File "/usr/local/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request↵    connection_type=connection_type)↵  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 1322, in request↵    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)↵  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 1072, in _request↵    (response, content) = self._conn_request(conn, request_uri, method, body, headers)↵  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 996, in _conn_request↵    conn.request(method, request_uri, body, headers)↵  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request↵    self._send_request(method, url, body, headers, encode_chunked)↵  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request↵    self.endheaders(body, encode_chunked=encode_chunked)↵  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders↵    self._send_output(message_body, encode_chunked=encode_chunked)↵  File "/usr/local/lib/python3.6/http/client.py", line 1065, in _send_output↵    self.send(chunk)↵  File "/usr/local/lib/python3.6/http/client.py", line 986, in send↵    self.sock.sendall(data)↵  File "/usr/local/lib/python3.6/ssl.py", line 965, in sendall↵    v = self.send(data[count:])↵  File "/usr/local/lib/python3.6/ssl.py", line 935, in send↵    return self._sslobj.write(data)↵  File "/usr/local/lib/python3.6/ssl.py", line 636, in write↵    return self._sslobj.write(data)↵BrokenPipeError: [Errno 32] Broken pipe↵"
type
:
"Internal Server Error"

**Comment by JimVanEeden** [comment]
Should be resolved now. Sorry for the late response, we were at a conference yesterday.
