### ISSUE TITLE
LightRiders - Cannot Set Active Bot Revision

### ISSUE THREAD

**Issue by rogster001** [riddlesio/issues#29]
After the Lightriders rule change I had to disable my bot while i got the random start implemented. I managed to upload the revision and all tests fine. However I cannot now set it to active - The little Icon is greyed out. I have tried on a couple of different browsers. Does anybody know what the problem is - generic fault at present?
One other user has responded on the discussion page to say this is happening to them also.

**Comment by rogster001** [comment]
I was able to set the active version just now. Some other people had reported this on the website though.

**Comment by JimVanEeden** [comment]
There was an error with upload yesterday, which caused this. Sorry for the late response, we were at a conference yesterday.
