### ISSUE TITLE
C++ threading support

### ISSUE THREAD

**Issue by mkbehr** [riddlesio/issues#30]
Opening an issue after discussion in [this thread](https://starapple.riddles.io/competitions/light-riders/discussions/discussion/7b06178d-e6ee-49e3-b8ab-3a153b631395/1). The light riders setup doesn't work with threading in C++ right now: trying to use std::thread gives a linker error ("undefined reference to `pthread_create'"). AFAIK this can be fixed by adding -pthread to the compiler flags.

**Comment by nikovanmeurs** [comment]
We'll implement this as part of the next sandbox update, as mentioned in the thread.

**Comment by JimVanEeden** [comment]
This should be fixed now
