### ISSUE TITLE
Compile issues with D

### ISSUE THREAD

**Issue by spelinski** [riddlesio/issues#31]
Attempted to upload a simple D bot and got the following in the compile log

> xargs: invalid option -- 'O'
Usage: xargs [OPTION]... COMMAND [INITIAL-ARGS]...
Run COMMAND with arguments INITIAL-ARGS and more arguments read from input.

**Comment by nikovanmeurs** [comment]
Thanks for letting us know, we'll look into this as soon as possible.

Could you send your bot to niko [at] riddles [dot] io so we have something to test with?

**Comment by spelinski** [comment]
Forgot to update here. Got it sent with the subject "D language bot for light rider". Thanks for the help.

**Comment by JimVanEeden** [comment]
This should be fixed now
