### ISSUE TITLE
Non-Light-Rider matches being shown on the Light Riders homepage

### ISSUE THREAD

**Issue by jmerle** [riddlesio/issues#32]
This strange thing just happened:

![Screenshot](https://i.imgur.com/DiGPfWP.png)

This match is being played here:
https://www.riddles.io/embed/match/17696f1a-6545-4904-bff6-b39b7b7d1f98

While I'm writing this, it has changed to an Ultimate Tic-Tac-Toe match:
![UltimateTicTacToe](https://i.imgur.com/s4gfumy.png)

And the match being played:
https://www.riddles.io/embed/match/4aef7eab-d749-40af-9349-8a24cfcf3701

**Comment by nikovanmeurs** [comment]
Thanks for letting us know. I'm looking into it right now.

**Comment by nikovanmeurs** [comment]
This should be fixed now. Please let us know if you still experience this issue.

**Comment by jmerle** [comment]
Yep, it's working correctly, thanks!
