### ISSUE TITLE
Stuck at "Waiting for match to be played..." (Light Riders)

### ISSUE THREAD

**Issue by bkiers** [riddlesio/issues#33]
When trying to challenge another bot in the Light Riders competition, the page keeps loading with the message `Waiting for match to be played...`

**Comment by nikovanmeurs** [comment]
Thanks for letting us know. We're currently experiencing more problems with the light riders competition (no ranked matches). This is probably related.

**Comment by nikovanmeurs** [comment]
Should be fixed now.

**Comment by bkiers** [comment]
Cool, thanks!
