### ISSUE TITLE
Rust starter bot

### ISSUE THREAD

**Issue by Naalunth** [riddlesio/issues#34]
Hey, I wrote a Rust starter bot for Light Riders. You can find it here <https://github.com/Naalunth/lightriders-starterbot-rust>.

You should be able to run it by running `cargo run --release` in the folder.

Alternatively, you can compile the bot with `cargo build --release` and manually start the executable in `./target/release/`.

As for the issues with cargo needing a network connection, I cleared my cargo caches and compiled it offline just fine (using the latest stable release v1.18.0). As long as no dependencies are added, no network connection is required.

**Comment by Naalunth** [comment]
Though I should add, it would be immensely useful, if you allowed the use of the crate `rand`, as Rust has no RNG implementation in the standard library.

**Comment by JimVanEeden** [comment]
Thank you :)

I'll add it to my TODO list, but it might be a while before it's actually implemented.

**Comment by Naalunth** [comment]
How long would you say implementation will take? Can I rely on the fact, that it will be available when the bot submission period ends (October 23rd)? Also, is it acceptable if I include a few crates from <https://crates.io/> — something along the lines of `libc`, `rand` and `simd`, to have functionality present in virtually every other respectable programming language — in my project (see <http://doc.crates.io/source-replacement.html>)?

**Comment by Naalunth** [comment]
Also please consider using nightly Rust, it's way more fun than boring old stable Rust 😄

**Comment by JimVanEeden** [comment]
I'm not sure, I'll probably have some time for it this month. But we've tried to implement it before and had quite some trouble with Rust, so depending on how that goes it might take a while. Hope to get it done before the Light Riders finals start.

**Comment by JimVanEeden** [comment]
Rust support has been implemented. You can check the getting started page and select Rust to see the particulars. I've added two libraries you can include in your project, the others will not be available.
