### ISSUE TITLE
Incorrect timebanks from engine?

### ISSUE THREAD

**Issue by pepijno** [riddlesio/issues#35]
In some of my games the timebanks the bot receive do not match the time spend of the process. At the start of each turn the bot outputs the current time spend by the process and for example in the game https://starapple.riddles.io/competitions/light-riders/matches/121a2ec0-5410-4924-8a1b-6ad7d3acbd49 at the start of round 17 the bot outputs an elapsed time of 6.60235 seconds while the engine gives a remaining time of 351 in the timebank, meaning that almost the entire 10 seconds have been used, plus the additional 200 ms for each move. Is there any way that this discrepancy can be explained?

**Comment by JimVanEeden** [comment]
This is a tough one because I don't think it has anything to do with the code that runs the matches. It might have something to do with the server, but that'll be hard to find. We will put it on our list and investigate it.

**Comment by JimVanEeden** [comment]
I'm closing this as the discussion has picked up in https://github.com/riddlesio/issues/issues/37
