### ISSUE TITLE
Can't edit account

### ISSUE THREAD

**Issue by olejorgenb** [riddlesio/issues#36]
The save button is gray and un-clickable. I have changed at least one of the fields (eg. country)

**Comment by JimVanEeden** [comment]
Did you enter your current password? (bottom field)

**Comment by olejorgenb** [comment]
Yes. Well I had before when trying to change password - tried it again now: no dice. I also tried another browser (chromium)

**Comment by JimVanEeden** [comment]
I'm pretty sure one of the fields is not correct (i.e. first name is to short or something). But we can't really test your particular case ourselves. I've tried with my own account and it works fine.

**Comment by olejorgenb** [comment]
Seems  "special" chars in the name isn't accepted. I have a 'ø' in my name which prevents saving. (The register page doesn't have the same validation or it has been changed)

**Comment by JimVanEeden** [comment]
Alright, nice find! That was indeed the problem. The regex testing validation for first name and last name wasn't the same for the sign up page as for the account edit page. This will be fixed in the next website update. Thanks!
