### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by nickschuch** [riddlesio/issues#38]
Failed to compile with Go.

Getting the following error:

```
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
```

**Comment by JimVanEeden** [comment]
That warning always pops up, it's not related to the compilation problem. But what is weird however, is that you don't see anything. Does your bot compile correctly locally?

**Comment by nickschuch** [comment]
Yep, compiles locally. Looks like it now gets to "input test failed" and doesn't go any further. Nothing in the output (except for "No log").

**Comment by nickschuch** [comment]
oooh! I now have output!
