### ISSUE TITLE
About laser-mine explodes

### ISSUE THREAD

**Issue by sunnychow** [riddlesio/issues#39]
According to the [document](https://booking.riddles.io/competitions/ms.-hack-man-internal/getting-started), 
> B[ticks] for a laser-mine, where [ticks] is the amount of rounds before the mine explodes

May I ask could just be B if it is not going to explode? (means it could be picked up by player?)

**Comment by JimVanEeden** [comment]
That's actually the case already, I've updated the document to make that clear. Thanks
