### ISSUE TITLE
Light-riders - Can't upload bot

### ISSUE THREAD

**Issue by pruzze** [riddlesio/issues#40]
Every time I try to upload a new bot the test match never ends, it seems to run for ever.

<img width="726" alt="cantuploadbot" src="https://user-images.githubusercontent.com/409539/28925071-0ee28046-7864-11e7-9cf4-25f1fa015786.png">

**Comment by JimVanEeden** [comment]
I have the same problem. We're going to look into it right now. Will keep you updated.

**Comment by JimVanEeden** [comment]
Fixed now, thanks a lot for your report :)
