### ISSUE TITLE
C++ connect four starter bot

### ISSUE THREAD

**Issue by afvanwoudenberg** [riddlesio/issues#41]
I'd like to submit a C++ starter bot for four in a row:
<https://github.com/afvanwoudenberg/c4bot>

The repo includes a Makefile. 
To build the bot locally:
make
To add the source files to a zip file that can be uploaded to the riddles.io platform:
make zip

I'm not attaching any license to the software.

**Comment by JimVanEeden** [comment]
Thanks a lot! I checked it and it looks good, so it's now available on the How To Play page :)

**Comment by afvanwoudenberg** [comment]
Awesome!
