### ISSUE TITLE
Link to booking

### ISSUE THREAD

**Issue by Bolukan** [riddlesio/issues#42]
I would like to have a link on the pages:
https://docs.riddles.io/ms-hack-man/api
https://docs.riddles.io/ms-hack-man/rules
https://docs.riddles.io/ms-hack-man/examples
to the page
https://booking.riddles.io/competitions/ms.-hack-man

**Comment by jmerle** [comment]
To add on to that, it would be nice if there would be a way to go from the home of the docs back to riddles.io, and to implement the concept above for all contests (as an example: https://docs.riddles.io/go/rules would also have a link to https://playground.riddles.io/competitions/go).

**Comment by JimVanEeden** [comment]
Good points, will be implemented soon.

**Comment by JimVanEeden** [comment]
Done, you'll find the links on the left side of the header. You can close this issue if you are satisfied :)

**Comment by Bolukan** [comment]
Satisfied
