### ISSUE TITLE
Gravatar isn't displayed.

### ISSUE THREAD

**Issue by Bolukan** [riddlesio/issues#46]
This is more a general topic than to this contest, but I didn't find a general forum. I've registered at gravatar and set a profile picture, however it isn't displayed.

So I compared the hash shown at gravatar with my email hash from the replay json data, they don't match. When converting my email to lowercase before applying the md5 as described on gravatar itself, I get the gravatar hash. If I skip that and keep capital letters in my mail address, I get the hash provided in the replay. Long story short: would you mind calling toLower before generating the hash?

To courtesy of eulerscheZahl

**Comment by JimVanEeden** [comment]
Didn't know that :)

It's updated now, thanks for your report.
