### ISSUE TITLE
If an armed laser-mine is hit, it will go off immediately.

### ISSUE THREAD

**Issue by Bolukan** [riddlesio/issues#47]
The rules state: "If an armed laser-mine is hit, it will go off immediately." 
Are unarmed laser-mines (not picked up yet) excluded? I see no check for ticks != null. 
If I read wrong: sorry.

https://github.com/riddlesio/hack-man-2-engine/blob/7493a9df7be228b3214ea393ed3cb12420c89731/src/java/io/riddles/hackman2/game/board/HackMan2Board.java#L355

**Comment by JimVanEeden** [comment]
Keen eye, this was a bug. Fixed now.
