### ISSUE TITLE
Possible disadvantage for opponent when my bot uses too much memory

### ISSUE THREAD

**Issue by smiley1983** [riddlesio/issues#48]
I can't verify whether my memory consumption actually caused this malfunction in my opponent's bot, but it happened around the same time my bot's memory consumption exceeded 200MB:

[game replay](https://starapple.riddles.io/competitions/light-riders/matches/95078e8b-4b3b-4813-a7bc-746547ba99ce)

From my bot's log, on turn 54 it had consumed 22242816 words on the heap (probably about 178MB) and on turn 55 it had consumed 25579520 words (probably about 204MB). On turn 59 my opponent seemed to suffer some sort of error.

It may have been coincidence - maybe my opponent also ran out of memory at about that time, but I thought I should raise it here just in case.

Since seeing this error I've made it clear the old parts of the data structure periodically when it grows too large (previously skipped this to save processing time, because in most games it doesn't manage to exceed 200MB).

**Comment by nikovanmeurs** [comment]
This is certainly possible as resource allocation is currently shared. We are currently working on a new sandbox which splits the resource allocation for all bots. I expect that we can run the first tests with the new sandbox at the end of next week and release it for general availability in two weeks.

Note that your bot will be limited to 200mb ram when the new sandbox goes live. This is a hard limit, so your bot will crash if it exceeds the allocated amount.

I'll keep this issue open and post periodic updates until the new sandbox is deployed so you can track its status.

**Comment by nikovanmeurs** [comment]
It'll take a bit longer until this issue is resolved; we're in the process of making several behind the scenes changes to the match runners. We'll be releasing all of these changes at once in about a month.

**Comment by nikovanmeurs** [comment]
Feature is currently being tested and will be rolled out next week if everything goes well.

**Comment by nikovanmeurs** [comment]
The sandbox update has been deployed to the production environment. As such I'm closing this issue.
