### ISSUE TITLE
download IO log (and Error log) of match logs

### ISSUE THREAD

**Issue by Bolukan** [riddlesio/issues#49]
I would like to have the possibility of downloading the logs with a button. Now I have to select the text, copy it to a notepad-app and save it with the appropriate name.
I suggest we get download button(s) in the match log screen. My primary intrest is the IO log, but I guess other people also like the Error log. When pushing the button, I would like to have the file the GUID as filename with appending extensions like .io or .error

**Comment by nikovanmeurs** [comment]
Thanks for the feature request. The feature is up for scheduling during tomorrow's team meeting.

**Comment by bonjowi** [comment]
Logs can now be downloaded on the match dump page.
