### ISSUE TITLE
Visualizer step forward uses small steps

### ISSUE THREAD

**Issue by melsonius** [riddlesio/issues#5]
When stepping through a game, step back (left arrow) steps back one full round, but going forward (right arrow) only steps forward a fraction of a round.  Perhaps this was intentional, but it makes stepping back and forth through a game difficult.  

I really like the small steps for when the game is just playing through, but I think stepping should be full rounds, or, at the very least, the same in both directions.  Thoughts?

**Comment by JimVanEeden** [comment]
I agree with your point and ideally I would like to have it stepping by rounds when clicking forward as well. However, due to the current implementation of the visualizer this was quite hard to achieve. We'll have a better look at it in a little white.

**Comment by Elirso** [comment]
Oh also, about the visualizer : Would it be possible to have the current round displayed ? Just to help debugging.

**Comment by JimVanEeden** [comment]
This can also be done in the next update of the visualizer, yes.

**Comment by Elirso** [comment]
btw this is now fixed

**Comment by melsonius** [comment]
Awesome!  Much better!
