### ISSUE TITLE
Ms Hackman: bugs still shown after hit by a mine

### ISSUE THREAD

**Issue by eulerscheZahl** [riddlesio/issues#50]
[replay](https://booking.riddles.io/competitions/ms.-hack-man/matches/03d2bae7-5281-47af-aa44-5843edc4bc93)
In round 86 the first row of the board, as passed to the AI, is:
`S,.,.,x,.,.,.,.,B1,P0;P1,E1,.,.,.,.,x,.,.,S`
so there is a bomb with timer 1 about to hit E1 with no way to escape

The input for the following round 87 is:
`S,.,.,x,.,.,.,.,.,E1,.,.,.,.,.,x,.,.,S`
There is no bomb anymore, but the enemy is still shown. To detect it as dead, one would have to keep track of mines on his own and clean that. In my opinion the enemy should be removed as well, making the line to
`S,.,.,x,.,.,.,.,.,.,.,.,.,.,.,x,.,.,S`

**Comment by JimVanEeden** [comment]
You are right, will be fixed in the next Ms. Hack-man update. Probably tomorrow or the day after.

**Comment by JimVanEeden** [comment]
Should be fixed now, thank you for letting me know. It turned out that I totally forgot to take 'dead' bugs out of the calculations.
