### ISSUE TITLE
Connect 4 Python3 Starter Bot

### ISSUE THREAD

**Issue by rileymcdowell** [riddlesio/issues#51]
I wrote a single-file python 3 bot for the four-in-a-row game which adheres to the API, has internal state and field classes, and randomly places disks into columns until the game ends or a column is over-filled. I though you might be interested in providing it as a starter bot.

The attached tar.gz can be uploaded directly to the playground to see it work.

[py3_starter_bot.tar.gz](https://github.com/riddlesio/issues/files/1404390/py3_starter_bot.tar.gz)

**Comment by JimVanEeden** [comment]
Thanks a lot! I've checked the code and it's available now on the How to Play page :)
