### ISSUE TITLE
Game does not end as draw when there is no more legal move available

### ISSUE THREAD

**Issue by csst** [riddlesio/issues#52]
Here is an example of my bot won a match that supposed to be a draw: 

https://playground.riddles.io/competitions/ultimate-tic-tac-toe/matches/ff05293a-f0e6-4b81-b99e-ff1cdd1bc6db

**Comment by csst** [comment]
Here is another example: https://playground.riddles.io/competitions/ultimate-tic-tac-toe/matches/f9926d9f-fc21-4675-81d8-37844e254f1b

**Comment by nikovanmeurs** [comment]
@JoostRiddles is looking into this. We'll patch this ASAP.

**Comment by JimVanEeden** [comment]
Fixed. Thanks a lot for your report!

**Comment by kritarthh** [comment]
https://playground.riddles.io/competitions/ultimate-tic-tac-toe/matches/f43fbddd-3854-47ee-bba5-5774083d4880
Same bug again?

**Comment by ClementChouteau** [comment]
Not right yet,
There is a draw when every small board is unplayable, I mean either won or full.
[](https://playground.riddles.io/competitions/ultimate-tic-tac-toe/matches/241e45fa-1e03-4cbb-81b9-0b413a6a8918)
