### ISSUE TITLE
MsHackman: collision with bug only applied to one player

### ISSUE THREAD

**Issue by eulerscheZahl** [riddlesio/issues#53]
[replay](https://booking.riddles.io/competitions/ms.-hack-man/matches/b8ae01bd-5f88-4d5f-ae41-6fb7f20343f0)
In the very last turn, both players share the same position (and are both coming from the same field). But when colliding with a bug, only player0 loses snippets.

edit:
the rules say: "If a bug collides with two players at the same time, both players lose snippets."

edit2:
This should fix it: [fork](https://github.com/eulerscheZahl/hack-man-2-engine/commit/135a1eabb2485015932e598b2d84c722ebf64783).
I did not test it, but it may help to identify the cause of the problem.

**Comment by nikovanmeurs** [comment]
Thanks for the bug report. @JimVanEeden could you look into this?

**Comment by JimVanEeden** [comment]
Thanks eulerscheZahl! You've got a pretty keen eye; that was the problem indeed.

I've fixed the bug straight away by copying the edits in your fork. Next time you can create a pull request as well if you want so I can just merge it after testing.

**Comment by eulerscheZahl** [comment]
Ok.
I wasn't sure if I should, as my changes were untested ;)
