### ISSUE TITLE
Four In A Row documentation outdated

### ISSUE THREAD

**Issue by jmerle** [riddlesio/issues#54]
In the Four In A Row documentation width and height are still talked about with `field_columns` and `field_rows` (which I assume to be taken from TheAIGames), which should be `field_width` and `field_height`. Not sure if it is the same in the starterbots and in other games ported from TheAIGames, so that might be worth checking.

Also, in the examples, `time_per_move` is set to 500, while on the servers it is run with the setting set to 200.

**Comment by JimVanEeden** [comment]
Thanks, I updated the pages.
