### ISSUE TITLE
Match View Showing Wrong Competition

### ISSUE THREAD

**Issue by rileymcdowell** [riddlesio/issues#55]
I've noticed that the match log for four-in-a-row is showing ranked matches for ultimate tic-tac-toe. This seems to be affecting multiple games.

https://playground.riddles.io/competitions/four-in-a-row/match-log/ranked/1
https://playground.riddles.io/competitions/texas-hold-%27em/match-log/ranked/1
etc.

The page and URL are visually fine (except that the matches are for a different game), but when you click a ranked match you see that the match played (and players) are from the wrong game.

**Comment by jmerle** [comment]
Something similar happened some months ago, so issue #32 might be relevant.

**Comment by JimVanEeden** [comment]
We found the problem. The website sends a wrong query to our API after an update we did yesterday. Will be fixed asap.

**Comment by JimVanEeden** [comment]
Should be fixed now
