### ISSUE TITLE
Clicking download on old revisions doesn't trigger the actual browser download

### ISSUE THREAD

**Issue by jmerle** [riddlesio/issues#56]
I happened to stumble upon this during the hackathon and was luckily able to trigger the download by hand. Basically, when you click on the download button to the right of a revision, it does download the file, but it doesn't trigger the download in the browser.

Console output:
![Image](https://i.imgur.com/uYo5t7q.png)

OS: Windows 10
Browser: Chrome 61.0.3163.100

**Comment by nikovanmeurs** [comment]
Thanks for letting us know. We'll be fixing this ASAP

**Comment by nikovanmeurs** [comment]
The fix has just been deployed.
