### ISSUE TITLE
Disable "Engine out" to stdout

### ISSUE THREAD

**Issue by claha** [riddlesio/issues#57]
Would it be possible to add a setting to the "wrapper" part of wrapper-commands-json so that we don't get all the "Engine out"/"Engine in" etc. on stdout? When running lots of games locally it would be nice to be able to supress this.

**Comment by JimVanEeden** [comment]
Yes this is possible, I'll put it on my TODO list

**Comment by JimVanEeden** [comment]
I just published a new release with this feature implemented. Add `"wrapper": "suppressEngineIO": true` to your wrapper-commands.json

[https://github.com/riddlesio/match-wrapper/releases/tag/1.4.0](https://github.com/riddlesio/match-wrapper/releases/tag/1.4.0)
