### ISSUE TITLE
Test match not loading

### ISSUE THREAD

**Issue by eulerscheZahl** [riddlesio/issues#59]
When I upload a new version of my bot, I get a match against a dummy opponent.
But the match just keeps loading (for example [this](https://booking.riddles.io/competitions/ms.-hack-man/matches/af5f9d8f-0105-43f6-87cd-9721724e5623) one).
The [embed](https://www.riddles.io/embed/match/af5f9d8f-0105-43f6-87cd-9721724e5623) match works fine.

**Comment by JimVanEeden** [comment]
For me it works fine, can you try logging out, logging in, and then refreshing the page on that first link?

**Comment by eulerscheZahl** [comment]
I just tried it, still loading - while I can view the second link even when not logged in.

Ubuntu 16.04.3 LTS
tested with Chromium 62.0.3202.62, Mozilla Firefox 56.0, epiphany 3.18.11, Google Chrome 62.0.3202.62

**Comment by JimVanEeden** [comment]
Alright we'll investigate this a bit more, thanks.

**Comment by JimVanEeden** [comment]
Issue is fixed now :) Thanks for the report.
