### ISSUE TITLE
Update compiler flags for C# to allow unsafe code (aka pointers)

### ISSUE THREAD

**Issue by timvdh1** [riddlesio/issues#60]
please add the following two flags to the mcs compilation process 

-unsafe -optimize

https://www.systutorials.com/docs/linux/man/1-mcs/

**Comment by nikovanmeurs** [comment]
Will do. This'll be released with the next version of the sandbox

**Comment by timvdh1** [comment]
Is there any indication on when the next version of the sandbox will be released?

**Comment by nikovanmeurs** [comment]
I'll be releasing an intermediate version containing the C# flags today.

**Comment by nikovanmeurs** [comment]
The update has just been deployed
