### ISSUE TITLE
Cannot upload bot

### ISSUE THREAD

**Issue by redsalmon91** [riddlesio/issues#61]
Uploaded bot fails every time with message "cannot upload bot"
Home page showing failed uploads as as "Compiling, Upload completed" (forever)

**Comment by csst** [comment]
![erro_upload](https://user-images.githubusercontent.com/9031670/32401898-0b3953b0-c0d6-11e7-9c1e-8f4fa81b7c7c.png)

**Comment by Kaligule** [comment]
Same problem for me.

![screenshot_2017-11-04_10 11 21](https://user-images.githubusercontent.com/3586246/32404052-c1b68dac-c148-11e7-8af3-94b7d0a73d8d.png)

I tried in different browsers (chrome in the screenshot) and the problem persists after 8 hours. What information do you need to debug?

**Comment by nikovanmeurs** [comment]
This is due to the load created by the Light Riders finals. It's not like the process failed, it's just that there are far more matches enqueued than normal. This currently causes significant delays for running test matches

**Comment by Kaligule** [comment]
I would still say that "Upoad failed" sends the wrong message to the user. The natural reaction is to try upload the bot again (and again) which makes the problem even worse.

**Comment by nikovanmeurs** [comment]
There's definitely a mismatch in communication there. I'll throw this in at the next team meeting to see if we can somehow make this more transparent.

**Comment by Kaligule** [comment]
It seems that bots can be uploaded again. Old uploads are still in the eternal compiling loop.
