### ISSUE TITLE
Go starter bot - Ms Hack Man

### ISSUE THREAD

**Issue by s7aesis** [riddlesio/issues#62]
Hi, I made a starterbot for ms hack man over here: https://github.com/s7aesis/ms-hack-man-starterbot.

There were no errors or warnings when I uploaded it to the site.

**Comment by nikovanmeurs** [comment]
Thanks for the link. We'll publish the starter bot after my colleague @JimVanEeden has reviewed the code.

**Comment by JimVanEeden** [comment]
Thanks, will be happening next week as we're currently out of the country.

**Comment by JimVanEeden** [comment]
I've checked the code and looks good, so it's available now. Thanks a lot!
