### ISSUE TITLE
Title of login page is quite generic 

### ISSUE THREAD

**Issue by armf** [riddlesio/issues#63]
Hi, I use a password manager for storing and auto-filling credentials on login pages. The password manager ([KeePassX](https://www.keepassx.org/)) uses the window title to correlate webpages with the respective credentials. Unfortunately riddle.io's login page title just says "Login" which is too generic for this purpose. I'd love to see this changed to "Riddle.io - Login" or "Login to Riddle.io" or something similar that uniquely distinguishes riddle.io's login page from others.

Of course this is only a very minor annoyance and I'm not at all disappointed if it's not going to be changed. But since it's presumable also only a small change I thought I put it here for your consideration. Thanks!

**Comment by nikovanmeurs** [comment]
Thanks for letting us know, we'll be fixing this somewhere next week.

**Comment by nikovanmeurs** [comment]
The title has been changed, thanks for your feedback.
