### ISSUE TITLE
Golad: show last opponents move

### ISSUE THREAD

**Issue by pepijno** [riddlesio/issues#65]
Can the engine output the last move of each opponent at the start of a turn? Golad is a game of perfect information so the last opponents move is available to each bot but letting the engine output the last move potentially saves computing time for the bots.

**Comment by JimVanEeden** [comment]
This has been added now. The move is given the same as your bot should output it, except the spaces are replaced by underscores, so `update player1 move birth_9,6_12,2_13,4` for instance (if you are player0).
