### ISSUE TITLE
GOLAD C++ Starter bot crashes

### ISSUE THREAD

**Issue by redking00** [riddlesio/issues#66]
The board member of the Bot class is not initialized to NULL during construction. A new Board instance may not be created when the first update command arrives.

**Comment by JimVanEeden** [comment]
Thank you for your report, will be fixed :)

**Comment by nikovanmeurs** [comment]
@JimVanEeden here's the patched starterbot. Can you make it available through the website?

[golad-starterbot-cpp.zip](https://github.com/riddlesio/issues/files/1501596/golad-starterbot-cpp.zip)

**Comment by JimVanEeden** [comment]
It's updated, might a bit until the cache is refreshed.
