### ISSUE TITLE
MsHackman: resetting bomb timer

### ISSUE THREAD

**Issue by eulerscheZahl** [riddlesio/issues#67]
As the topic popped up in the [forum](https://booking.riddles.io/competitions/ms.-hack-man/discussions/discussion/757d819e-97cd-4036-99f1-b2beb4dd63f6/1), I'm creating an issue for it:
it is possible to reset the timer of a bomb by placing another bomb on top of it.
For a possible fix see my [pull request](https://github.com/riddlesio/hack-man-2-engine/pull/1)

**Comment by JimVanEeden** [comment]
This is fixed now, thank you.
