### ISSUE TITLE
.cc files treated as C, not C++

### ISSUE THREAD

**Issue by tombsar** [riddlesio/issues#68]
I typically use the .cc file extension for C++ code projects*, however when uploading to riddles.io it tries (and fails) to compile the code as C99.

*This is not just my convention; many pieces of software (notably GNU Make) recommend using .cc as the file extension for C++ code.

**Comment by JimVanEeden** [comment]
You are right, for some reason we recognized .cc files as C. This will be fixed in the next update of the compiler. Thanks for your report.

**Comment by nikovanmeurs** [comment]
The fix has just been deployed
