### ISSUE TITLE
Tooltips not displaying

### ISSUE THREAD

**Issue by tombsar** [riddlesio/issues#69]
On a competition page (https://booking.riddles.io/competitions/ms.-hack-man), once logged in there is a list of revisions for my bot. Next to each revision is a series of buttons with icons: power, play, list, and download. While the play and list buttons have tooltip texts explaining their functions, the power and download buttons do not. While I can guess at what they do, it would be good to have a tooltip to make it clear, especially for the "power" button. (From the HTML source it looks as though there is text that is supposed to be displayed, but for some reason it is not appearing).

I'm using Firefox 52.4.0

**Comment by nikovanmeurs** [comment]
Thanks for letting us know, there should indeed be tooltips on all the buttons. Well look into it

**Comment by bonjowi** [comment]
Hi tombsar, I've found and fixed the problem. Title tags on children of buttons do not work in firefox (the other two are anchors). The fix will be online with the next deployment of the front-end. Thank you

**Comment by nikovanmeurs** [comment]
The update been deployed, I'm closing this issue.
