### ISSUE TITLE
OCaml starter bot submission

### ISSUE THREAD

**Issue by smiley1983** [riddlesio/issues#7]
Hi, I've made a starter bot in OCaml:
[LightRiders OCaml starter](
https://github.com/smiley1983/lightriders-ocaml-starter)

It can be compiled with this command:

`ocamlbuild -lib unix main.native`

Please let me know if there's anything I can do to help make OCaml available on the site.

Best regards,

**Comment by JimVanEeden** [comment]
Thank you, I will have a go at it the coming week.

**Comment by nikovanmeurs** [comment]
We have tentative support for OCaml in our test environment. We'll deploy the update tomorrow if everything works as expected.

**Comment by smiley1983** [comment]
Great! Thank you for your work on this.

**Comment by nikovanmeurs** [comment]
The sandbox has been updated, we now have support for OCaml.

Have fun coding!
