### ISSUE TITLE
GOLAD - Bot upload fail

### ISSUE THREAD

**Issue by rogster001** [riddlesio/issues#71]
I and others are getting a problem where the upload of a new revision is failing at the test match stage with the message 'upload could not be completed'

it passes upload though, then compiles ok, then input test is ok but crashes on trying to run a test match. Also the report for the test match shows 5000 ms MAX and 200ms per move when it should be 10000/100 Can you please take a look. ta.

**Comment by JimVanEeden** [comment]
Thanks, everything should be working again now. We had a small issue in the database that caused this.

The test match settings are also updated now, but it might be a bit of time before you see it because of the caching.
