### ISSUE TITLE
Haskell starterbot - Texas Hold 'em

### ISSUE THREAD

**Issue by Kaligule** [riddlesio/issues#72]
I wrote a starterbot for Texas Hold 'em in Haskell and it is availible here:
https://gitlab.com/Kaligule/poker_starterbot_haskell

**Comment by nikovanmeurs** [comment]
Thanks for the link. @JimVanEeden will make it available on the website after a review.

**Comment by JimVanEeden** [comment]
Thanks so much! I've check the code and everything looks great so it's available now on the competition :)

**Comment by Kaligule** [comment]
Your welcome. In case I update the bot, how can I trigger an update? Should I just raise a new issue?

**Comment by nikovanmeurs** [comment]
Yes, that would be the easiest way.
