### ISSUE TITLE
Match Log Filter

### ISSUE THREAD

**Issue by tiramon** [riddlesio/issues#75]
The Match Log does only contain the value 'Ranked' in the filter 'Go to'.

But is doesn't filter anything.

Imho
The Filter 'Ranked' should only show games started by the system that are ranking relevant.
Maybe add one or two other filters 'Challenges', 'Submissions' to filter those 2 other kind of games.

**Comment by JimVanEeden** [comment]
That's actually not a filter but a schema selector. Currently there is only one schema 'ranked'. But when there is a lock-down/finals and stuff like that you can go to those schemas.

The only filter we currently have is the 'my matches' filter, but we're going to work on a filter with a lot more options.
