### ISSUE TITLE
Uploader GOLAD

### ISSUE THREAD

**Issue by rogster001** [riddlesio/issues#76]
Hi - Can the upload facility please be checked - I and others are finding it sticking - the bot overview section shows the 'compilation' icon whirling away and the ' i ' next to the bot uploader shows upload failed.

**Comment by JimVanEeden** [comment]
This seems to be a problem with the Google Cloud servers. We're looking in to it but it might be out of our hands.

**Comment by JimVanEeden** [comment]
It seems to have been fixed now.
