### ISSUE TITLE
502 bad getaway

### ISSUE THREAD

**Issue by RuddeK** [riddlesio/issues#77]
When trying to upload a bot on four-in-a-row the upload fails. Firefox console says a error 502, bad getaway occurs. The reason for the error is 'CORS header "Access-Control-Allow-Origin" is missing.' The missing header means Firefox and chrome (I haven't tested others) blocks the request. 

At times the upload is successful, although the rate is about 10 fails per successful upload. 
A successful upload gets code 200 and no output to the console. 

Issue probably related to #76.

**Comment by JimVanEeden** [comment]
This is the same weird error we had yesterday. We have to look into the problem some more, because it's not acceptable that this is happening. Very weird error though, we're not sure where it's coming from all of a sudden. It kind of fixed itself as wel yesterday.

**Comment by RuddeK** [comment]
Today I didn't manage to upload anything. Chrome and Firefox throws error 500: Internal server exception.

**Comment by JimVanEeden** [comment]
We're still working on this. It occasionally occurs.

**Comment by JimVanEeden** [comment]
Closing as we've fixed our stability issues.
