### ISSUE TITLE
Not all bomb explosions are rendered (Ms. Hack-Man 2)

### ISSUE THREAD

**Issue by tombsar** [riddlesio/issues#79]
According to the Ms. Hack-Man 2 game logic, new bombs placed in the blast of another exploding bomb will detonate instantly (during that same turn). The game visualizer does not currently draw these instant explosions, sometimes making it hard to understand what happened during a match.

For example, round 160 of the following match shows the situation: https://booking.riddles.io/competitions/ms.-hack-man/matches/d401533e-41e3-4d34-bb52-4ebbf0275ba6 lazy_bot places a bomb on the same turn as being hit by an explosion, and eulerscheZahl_bot takes damage despite there being no visible secondary blast.

**Comment by eulerscheZahl** [comment]
Should be [fixed](https://booking.riddles.io/competitions/ms.-hack-man/discussions/discussion/591cc52c-cfe7-4e0d-82ac-24493bf8a58a/1), but apparently isn't. Off by one?

**Comment by JimVanEeden** [comment]
Ah well it seems the difference here with the previous problem is that this bomb explodes as soon as it's placed and the matchviewer doesn't take that into account. I'll have a look at it.

**Comment by tombsar** [comment]
Has this been fixed? I noticed some recent match replays do have the knock-on explosions rendered (although the older ones haven't changed).

**Comment by eulerscheZahl** [comment]
The issue can be close, see [this](https://booking.riddles.io/competitions/ms.-hack-man/matches/1db1d2ac-f29b-4b5f-a4a4-4cdb0b866592) for example.
When you look at the changes, the generated json output was modified. So this fix can't affect older matches that already have been played.

**Comment by tombsar** [comment]
There still seems to be a regression. Bombs used to turn green when exploding, but since this change they look inactive on the turn they explode.

**Comment by JimVanEeden** [comment]
Oh yea sorry guys, this issue had been fixed. Not for the old matches though because I had to change some stuff in the engine's output in order to fix it. I'm going to have a look at why they don't turn green anymore, but I'm going to close this issue.
