### ISSUE TITLE
Bot has not gotten any matches

### ISSUE THREAD

**Issue by RenegadeLucien** [riddlesio/issues#8]
My bot (Renegade) has not played a single match since it was activated this morning. Other bots such as Jaeger have played as many as nine matches in this time, and another bot called zhlucs that was activated after mine got a match almost immediately, while mine has still gotten nothing. Am I just really unlucky, or is there some bug preventing me from getting any matches?

**Comment by JimVanEeden** [comment]
There is probably some issue with our backend or data that prevents your bot from entering the match schedule. We will look at it today. In the mean time, you can try to re-upload your bot and see if that helps.

**Comment by nikovanmeurs** [comment]
This is related to #3. We just deployed a new scheduling algorithm, please let us know if this works for you.

**Comment by RenegadeLucien** [comment]
I've gotten a couple matches since, but I believe they were challenges (they were unrated). Doesn't look like I'm in the match schedule yet.

**Comment by nikovanmeurs** [comment]
Have you tried uploading your bot again and activating the new submission?

**Comment by RenegadeLucien** [comment]
I just did a few minutes ago.

But it seems as though I did, at last, get a ranked match. (I'll close this issue if the new version also gets a ranked match.)
