### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by eulerscheZahl** [riddlesio/issues#80]
As in #74 the "Not Found" appears again for a few days. This in not limited to the FAQ page, but also affects the main page. Subpages for the contests are working fine, but I can only reach them through my browser history.
Tested with Ubuntu 14.04 and 16.04 and various browsers.
![notfound](https://user-images.githubusercontent.com/9901571/34142295-9a1903cc-e486-11e7-88ad-53da95eb0228.png)

**Comment by JimVanEeden** [comment]
We're aware, as I commented in #81, this is because of full queues in RabbitMQ which cause the to get so slow they timeout. All those pages use requests to RabbitMQ so they fail to load. We're working hard to fix this.

**Comment by JimVanEeden** [comment]
Closing as we've fixed our stability issues. (front-end isn't using RabbitMQ at all anymore by the way)
