### ISSUE TITLE
New bots have to wait too long to get matches (MsHackman)

### ISSUE THREAD

**Issue by eulerscheZahl** [riddlesio/issues#81]
Newly uploaded bots (when the user enters the game and doesn't already have a bot in the arena) take quite long to happen.
As the match making usually goes from first to last of the leaderboard but seems to be a little scrambled (1st, 3rd, 2nd for example - looking at the leaderboard before the round starts), I suppose a match queue, that contains several rounds of matches, not just one.
I didn't check for other games but observed that at MsHackman.

**Comment by JimVanEeden** [comment]
We're having some problems with our RabbitMQ queues lately, which gets overly full for some reason and then also gets very slow which causes the 'not found' timeouts. We're working very hard to fix that. So it's not surprising newly uploaded bots take a bit longer than usual as the queue is very full.

**Comment by JimVanEeden** [comment]
Closing as we've fixed our stability issues.
