### ISSUE TITLE
GOLAD upload fail / compiling...endlessly

### ISSUE THREAD

**Issue by rogster001** [riddlesio/issues#82]
I think we are having the same issue with the upload of Bot revisions as in

https://github.com/riddlesio/issues/issues/78 for Lightriders. - I am now advanced 3 unwanted bot revisions more and it is just stuck at compiling without actually being able to delete them or anything.

**Comment by JimVanEeden** [comment]
Still same problem sadly :( It's driving us nuts. We're narrowing down the issue but RabbitMQ is just getting super slow all the time and we don't know why exactly. Sadly the whole platform heavily relies on it so we can't just get rid of it. If there's anyone with knowledge of RabbitMQ we'd appreciate some help :0

**Comment by JimVanEeden** [comment]
Should be fixed (temporarily) now.

**Comment by rsmorley** [comment]
It looks like this is happening again. I'm having the same issue using the starter go bot for Ms. Hack Man.

**Comment by JimVanEeden** [comment]
Closing as we've fixed our stability issues.
