### ISSUE TITLE
Some mines remain active after exploding (Ms. Hack-Man 2)

### ISSUE THREAD

**Issue by tombsar** [riddlesio/issues#83]
As per the discussion here: https://booking.riddles.io/competitions/ms.-hack-man/discussions/discussion/f2a00321-da9f-4f1e-9a00-3edb1693ac5a/1

The latest engine update a few days ago seems to have broken bomb/mine behaviour. Mines that explode instantly (placed during the same round that the player is hit by another explosion) are incorrectly allowed to remain on the field, and continue to count down as though they had not already exploded.

**Comment by JimVanEeden** [comment]
This has been fixed now :) thank you for your report.
