### ISSUE TITLE
GOLAD Upload failed for unknown reason

### ISSUE THREAD

**Issue by PhilipCastiglione** [riddlesio/issues#84]
Uploading a new revision to my Python 3 bot fails with this error message.

The bot appears to upload successfully at first, it compiles, the input test passes, the test game runs. However just around the time I'm expecting the test game to finish, a step fails in some way, leading to this:

<img width="315" alt="screen shot 2018-01-12 at 10 25 11 am" src="https://user-images.githubusercontent.com/10751757/34852577-7503dd7c-f783-11e7-87fb-fb4b6dc1415e.png">

Here is a relevant submission log: https://starapple.riddles.io/competitions/game-of-life-and-death/my/bot-revisions/aafca57a-5549-4ee4-92e2-b0b2e52d8f24/submission-logs

**Comment by JimVanEeden** [comment]
Our backend has been a bit unstable lately. As far as I can see this has nothing to do with your bot, so if you try to upload again it will probably work.

**Comment by PhilipCastiglione** [comment]
Unfortunately the problem is persistent. These have been over the course of the last 24 hours or so, last one just now.

Any more information I could give you that would help?

<img width="682" alt="screen shot 2018-01-12 at 7 47 17 pm" src="https://user-images.githubusercontent.com/10751757/34866674-6fa9f7fa-f7d1-11e7-93d3-cf96796a9d45.png">

**Comment by JimVanEeden** [comment]
ermmm then this is probably a bug in your bot that causes our backend to crash for some reason (this should obviously not happen). I just tested with the python starterbot and it works just fine, so it might be your bot. Have you tried running it locally (with the workspace https://github.com/jmerle/ai-bot-workspace)?

I'm going to have a look at why our backend is crashing, but meanwhile you could try to see what's going wrong with your bot.

**Comment by PhilipCastiglione** [comment]
😅  I'll get the workspace running and see if I can find anything out.

**Comment by Trazarw** [comment]
I don't think is a bot source code problem.

Is the same for me from last night, I tried my current bot but also other brand new bots in different languages, sometimes the same source code works and sometimes it does not,

**Comment by PhilipCastiglione** [comment]
Looks like something has changed server-side, seems I can upload again. If you fixed something, thanks!

**Comment by PhilipCastiglione** [comment]
Ah seems things are just flakey. Uploading various starter bots in different languages is currently failing. Just tried uploading the C++ starter bot with the same (failure) outcome.

**Comment by JimVanEeden** [comment]
Closing, issue should not occur anymore as we've fixed stability issues.
