### ISSUE TITLE
Explode bombs test fails (Ms. Hack-Man 2)

### ISSUE THREAD

**Issue by tombsar** [riddlesio/issues#85]
I'm trying to build the Ms. Hack-Man 2 engine to run on my local machine, but the "explode bombs" test is failing. The test asserts that `getBombs().size() == 1`, but the engine returns 6.

Possibly related to the previous issues regarding bombs; do exploded bombs now remain in the bomb list where they were previously removed? If so, the test needs updating.

**Comment by JimVanEeden** [comment]
Done :) cleanUpBombs needed to be called.
