### ISSUE TITLE
API command for "end of match" (feature request)

### ISSUE THREAD

**Issue by tombsar** [riddlesio/issues#88]
I would like to print stuff at the end of a match (debug statistics, e.g. memory usage, total time taken, etc), but currently (unless I'm missing something) there is no way to do this; the game simply ends without sending anything further to the clients.

Would you consider adding an API message to facilitate this? e.g. `update game over` to indicate that the game has ended. More information, such as the final scores, would also be nice (could be achieved without further API changes by simply sending one last set of `update` messages, but not requesting an action afterwards).

**Comment by JimVanEeden** [comment]
This might be a nice idea, but I'd rather not updated existing engines with new API calls because this might cause bots to crash or print errors. So you can print it every round if you want to for now, and I'm going think about a feature like this in future engines.

**Comment by tombsar** [comment]
> I'd rather not updated existing engines with new API calls

Oh, of course not! I meant as something to consider for future games. Thanks for the response.

**Comment by JimVanEeden** [comment]
Cool, I'm going to close this issue for now then.
