### ISSUE TITLE
D programming language: old version doesn't run, can't upload new one

### ISSUE THREAD

**Issue by botrunner74** [riddlesio/issues#89]
From recent game of mine https://playground.riddles.io/competitions/light-riders/matches/31709ae2-ad75-45ea-9240-65ea0ee728ab/dump

```
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /executable_dir/run_ai)
Error relocating /executable_dir/run_ai: _Unwind_GetRegionStart: symbol not found
```

I've tried re-uploading, but compilation fails, but I can't see why:
https://playground.riddles.io/competitions/light-riders/my/bot-revisions/a061ef31-c059-410d-b8fd-0ab0dcadd197/submission-logs

**Comment by JimVanEeden** [comment]
Thanks, I'm going to look into this.

**Comment by JimVanEeden** [comment]
Fixed now :)
