### ISSUE TITLE
Compile Error: "Cannot deal with extension: .tar.gz"

### ISSUE THREAD

**Issue by rally25rs** [riddlesio/issues#9]
I was trying to make a JS bot. If I try to upload a .js file directly, it tells me that it requires a `.tar.gz`, `.rar`, or `.zip`.

I compressed my .js file to a .tar.gz and uploaded that.

```
tar -cvzf bot.tar.gz bot.js
```

Then I get a compilation error:

> Cannot deal with extension: .tar.gz

-----

If I re-compress as a `.zip` instead, then it gets a different compile error:

> WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.

**Comment by Honneamise** [comment]
the second one it is just a warning, i also get it ( my bot is in C and .zip ) but my bot is up and playing matches .

**Comment by JimVanEeden** [comment]
You have to upload a .zip file. .tar.gz and .rar files are not supported (yet).

The second one is indeed a warning, you always get that. Some server thing that we are still trying to get rid of.
