### ISSUE TITLE
Crypto-trader: minor output bug in overview page

### ISSUE THREAD

**Issue by SafPlusPlus** [riddlesio/issues#92]
At the overview page, when logged in, when having multiple bot revisions with multiple valid test results and assessments values, at "Best assessed" I expect the following values:
"`<bot_revision_number_with_best_assessment_value>" ($ <best_assessment_value>)`"

I believe that the bot_revision_number_with_best_assessment_value is displayed incorrectly here and instead shows the revision number with the best test value.

Currently this is showing in my overview:

```
Status
Best assessed 24 ($ 1406)
Best tested 24 ($ 5362)
```

And the stats for revision 24 are:

```24 $ 5362 ASSESS NOW```

My best assessed revision is actually revision 11:

```11 $ 1164 $ 1406```

**Comment by JimVanEeden** [comment]
Ah yes that's a bug, going to be fixed soon.

**Comment by JimVanEeden** [comment]
Fixed
