### ISSUE TITLE
Ultimate Tic Tac Toe: end of game

### ISSUE THREAD

**Issue by eulerscheZahl** [riddlesio/issues#97]
[replay](https://playground.riddles.io/competitions/ultimate-tic-tac-toe/matches/815bc6d9-bf76-43e6-9c13-18a26db61bcf).
There are no more valid moves, but I still get prompted for a move.

```
update game round 27
update game field .,1,0,0,1,.,1,0,1,.,1,0,0,.,.,1,0,1,.,.,0,0,0,.,0,1,0,.,.,1,1,.,.,0,0,0,0,0,1,1,0,1,0,1,1,.,.,1,1,.,0,1,.,.,0,.,.,1,1,1,1,1,1,1,0,0,.,0,.,0,.,.,1,.,0,.,.,0,.,.,.
update game macroboard 0,0,.,1,1,0,0,1,1
action move 9719

```

I think that the game should end with a draw instead. Note that there is no "-1" on the macroboard, indicating a valid move.

**Comment by JimVanEeden** [comment]
Yes this is a bug, will be fixed. Thanks :)

**Comment by JimVanEeden** [comment]
Should be fixed correctly this time.
